image: python:3.7

before_script:
  - python --version
  - echo "$CI_PROJECT_URL" | grep -q cee-gitlab.sandia.gov && INDEX="-i https://nexus.web.sandia.gov/repository/pypi-proxy/simple" && unset https_proxy http_proxy

stages:
  - Analysis and Tests

Unified Tests:
  stage: Analysis and Tests
  script:
    - ( unset https_proxy ; git fetch origin master )
    - if ! git diff --check origin/master HEAD -- . ':!src/jaqalpaq/_backports/_*' ; then echo "See above whitespace errors." ; exit 1; fi
    - if find . -iname '*.py' -exec grep -l -P '\t' {} + ; then echo 'Above files have tabs.' ; exit 1 ; fi
    - pip install $INDEX black && black --check --force-exclude 'src/jaqalpaq/_backports/_.*' .
    - ( unset https_proxy ; cd .. && rm -fr jaqalpaq && git clone --depth 1 "$(echo "${CI_REPOSITORY_URL}" | sed 's/jaqalpaq-extras.git/jaqalpaq.git/' )" )
    - ( cd ../jaqalpaq && pip install $INDEX -e .[tests] )
    - ( unset https_proxy ; cd .. && rm -fr qscout-gatemodels && git clone --depth 1 "$(echo "${CI_REPOSITORY_URL}" | sed 's/jaqalpaq-extras.git/qscout-gatemodels.git/' )" )
    - ( cd ../qscout-gatemodels && pip install $INDEX -e . )
    - pip install $INDEX -e .[qiskit,pyquil,cirq,projectq,pytket] && pytest
